name: Compile and Save Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2

    - name: Compile C++ code
      run: |
        if [ -e *.cpp ]; then
          clang++ Driver.cpp -o Driver
        fi

    - name: Save executable
      if: success() && -e my_program
      run: |
        mkdir -p executables
        mv my_program executables/
